e2e: use client-go's kubeconfig loaders
konflux-workspaces/workspaces pull request #130
Opened 2024-05-15 00:35 UTC by sadlerap

client-go does the right thing in more circumstances than we do.  On clusters, it should pick up credentials according to the secrets projected into the pod, while on desktop clients, it should respect `KUBECONFIG` env vars (defaulting to `~/.kube/config`).

This is a copy of what toolchain-e2e does during test initialization. See [init.go] and [kube_client.go] for more details.

[init.go]: https://github.com/codeready-toolchain/toolchain-e2e/blob/master/testsupport/init.go#L65-L74
[kube_client.go]: https://github.com/codeready-toolchain/toolchain-e2e/blob/master/testsupport/util/kube_client.go#L13-L20

2024-05-15 05:05 UTC, filariow requested changes
We are using this approach also in `e2e/hook/kubeconfig.go`. Should we update also that file?

2024-05-15 05:05 UTC, filariow commented on e2e/hook/host_client.go
> +		return nil, fmt.Errorf("error building config: %v", err)
```suggestion
		return nil, fmt.Errorf("error building client: %v", err)
```

2024-05-16 16:02 UTC, sadlerap commented
Yeah, I'll update `e2e/hook/kubeconfig.go` as well.

2024-05-16 16:15 UTC, filariow approved these changes

2024-05-16 16:33 UTC, merged